name: zart_player
description: "A Story Player For The Zart Z-Machine Interpreter"
publish_to: 'none'
version: 1.0.1
platforms:
  web:
topics:
  - zmachine
  - interactive-fiction
  - zork
  - zart
environment:
  sdk: ^3.10.3
dependencies:
  flutter:
    sdk: flutter
  zart: ^1.7.11
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.7
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/minizork.z3
    - assets/zart_logo.png